name: Terraform Provision GCP VM

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to run: apply or destroy'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

env:
  TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
  TF_VAR_gcp_service_account_key: ${{ secrets.GCP_SA_KEY }}
  TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0 # Specify a stable version

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        if: github.event.inputs.action != 'destroy'
        run: terraform plan -input=false

      - name: Terraform Apply / Destroy
        id: apply_or_destroy
        run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            echo "Running Terraform Apply..."
            terraform apply -auto-approve -input=false
          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            echo "Running Terraform Destroy..."
            terraform destroy -auto-approve -input=false
          else
            echo "Invalid action: ${{ github.event.inputs.action }}"
            exit 1
          fi